[build]
  publish = "."
  command = ""

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache"
